In [3]:
pip install numpy

  Using cached numpy-2.4.3-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Using cached numpy-2.4.3-cp314-cp314-win_amd64.whl (12.4 MB)
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
# Arithematic operations: + - * /
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b) # [5 7 9]
print(a * b) # [4 10 18]
print(a / b) # [0.25 0.4 0.5]
print(a - b) # [-3 -3 -3]

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[-3 -3 -3]


In [6]:
# Basic Mathematical functions
tri = np.array([0, np.pi/2, np.pi,1])
print(np.sin(tri)) # [0. 1. 0. 0.84]
print(np.cos(tri)) # [1. 0. -1. 0.54]
print(np.exp(tri)) # [1.4.81 20.09 2.72]
print(np.sqrt(tri))

[0.00000000e+00 1.00000000e+00 1.22464680e-16 8.41470985e-01]
[ 1.00000000e+00  6.12323400e-17 -1.00000000e+00  5.40302306e-01]
[ 1.          4.81047738 23.14069263  2.71828183]
[0.         1.25331414 1.77245385 1.        ]


In [10]:
# sorting arrays
val = [("popo",2008,7.2),("koko",2007,8.9),("Dodo",2009,6.5)]
dtype = [("Name","S10"),("Year",int),("GPA",float)]

arr = np.array(val, dtype=dtype)

print(np.sort(arr, order="Name"))
print(np.sort(arr, order="Year"))
print(np.sort(arr, order="GPA"))
print(np.sort(arr, order=["Year", "GPA"]))
print(arr)

[(b'Dodo', 2009, 6.5) (b'koko', 2007, 8.9) (b'popo', 2008, 7.2)]
[(b'koko', 2007, 8.9) (b'popo', 2008, 7.2) (b'Dodo', 2009, 6.5)]
[(b'Dodo', 2009, 6.5) (b'popo', 2008, 7.2) (b'koko', 2007, 8.9)]
[(b'koko', 2007, 8.9) (b'popo', 2008, 7.2) (b'Dodo', 2009, 6.5)]
[(b'popo', 2008, 7.2) (b'koko', 2007, 8.9) (b'Dodo', 2009, 6.5)]
